### ISSUE TITLE
Any chance to insert custom lyrics?

### ISSUE THREAD

**Issue by victorpinto** [6A/BeatSinger#2]
Just wondering if there is any way we could add custom lyrics without using musixmatch

**Comment by 6A** [comment]
I have some time to implement this today or tomorrow. Is there any specific way you'd like it to work? I was thinking about checking for a lyrics.json file in the directory of the song.

**Comment by victorpinto** [comment]
Checking for some kind of lyrics text file is what I was thinking, though I have no idea how you're spawning additional UI objects. I'm looking to put in a special message at the end of a song.. you would be an amazing person if this can work out!

**Comment by 6A** [comment]
Custom lyrics were added in 1ac9323. However I wasn't able to try it out, so I'd like it if you sent me one of the files you created so that I can make sure it works well!

**Comment by victorpinto** [comment]
I'm going to work on a lyrics file tonight, and i'll attach here when finished. Will  let you know if its working on my end as well.

**Comment by victorpinto** [comment]
[ThisGirlsrt.zip](https://github.com/6A/BeatSinger/files/2107820/ThisGirlsrt.zip)
I have not gotten this to work as of yet. The plugin still searches for the online lyrics. I have also tried naming the file lyrics.srt and that has not worked either

**Comment by 6A** [comment]
I unfortunately won't get my hands on my computer until Sunday night, but from what you've sent me, I can see your file is actually named `ThisGirl.srt.srt` and not `ThisGirl.srt`. Can you try removing the redundant extension? By default Windows hides extensions, so you'll have to make sure you only kept one `.srt`.

**Comment by PyroBillie** [comment]
Hi, I actually wanted to request the same thing, I have aloooot of lyric files synced up per song, to use in the Rocksmith customs as lyrics in game, is there a chance I can reuse those files? The files are created with Ultrastar creator (a small program to create files for karaoke purposes) it exports .txt files, in this format: #TITLE:Unknown Title
#ARTIST:Unknown Artist
#MP3:guitar.ogg
#BPM:338.27
#GAP:3805
: 0 2 0 Light
: 6 1 0  all
: 10 1 0  the
: 14 2 0  torches
: 26 2 0  and
: 31 1 0  wake
: 36 2 0  up
: 41 1 0  the
: 46 2 0  King
- 54
: 61 2 0 The
: 65 2 0  smoke
: 70 2 0  you've
: 75 1 0  ignored
: 85 1 0  is
: 89 2 0  a
: 94 2 0  flame
: 100 2 0  you
: 105 2 0  can't
: 113 1 0  contain

**Comment by 6A** [comment]
@PyroBillie I'm afraid this format is much harder to use than SRT or JSON for this purpose, sorry. The goal of the plugin is to display whole sentences all at once, not individual words (except if I missed something and you can actually know, using your format, what sentence appears at what time stamp in the song)

**Comment by PyroBillie** [comment]
Oh, to bad, but I hope someone will make a karaoke plugin eventually

**Comment by 6A** [comment]
Alright, I've done some testing and I know what's wrong. Unfortunately the solution is quite tricky, so I'm not sure about when I'll be able to push a fix. If all goes well, one will be ready by tomorrow night.

**Comment by 6A** [comment]
@victorpinto Please try again with the new version, it should now work fine with any file named `lyrics.srt` in the directory.
