### ISSUE TITLE
Beat Saber 1.17?

### ISSUE THREAD

**Issue by DenisSlobodyanyuk** [6A/BeatSinger#20]
Does this work on Beat Saver 1.17?
It's not listed in mod menu and no indication when playing. 
I tried to manually install Song Loader since I think the name in ModAssistant has changed. Song Loader GitHub page said it's in ModAssistant but it isn't listed there.

**Comment by 71** [comment]
I'm pretty sure that it's not compatible with BS 1.17. Unfortunately I no longer have a VR headset, so I can't work on an update :/ There was a PR to add support for 1.11 in #19, but it hasn't been accepted. Your best shot might be to port the update yourself, but note that testing the changes will take me some time, so you're better off forking the repo if you want to avoid long review times.
