### ISSUE TITLE
v0.4.1 doesn't see my lyrics.json

### ISSUE THREAD

**Issue by Proulxs** [6A/BeatSinger#6]
Here's the lyric.json file I was using for Rasputin (Funk Overload) map before the update. I didn't change the json file.
The online music still work. I have yet to try a srt because I never made any of those.

[lyrics.zip](https://github.com/6A/BeatSinger/files/2321111/lyrics.zip)

**Comment by 6A** [comment]
Fixed in https://github.com/6A/BeatSinger/releases/tag/v0.4.2.
