### ISSUE TITLE
Naming convention isn't all equal

### ISSUE THREAD

**Issue by Proulxs** [6A/BeatSinger#7]
Alot of mappers use the Freeek chart naming convention which mean putting the name of the singer/group into the "songSubName" and the mapper name's into the "authorName" chart label instead of the opposite. This result in the lyrics not being found since Welcome to my Life by MoeTheLion isn't a thing...

Since you already have a stop going on when local lyrics are found I assume you could add an easy solution by adding a new search on the to-do list and making it stop whenever the lyrics are found;
1) Search local lyrics.json
2) Search local lyrics.srt
3) Search "songName" by "authorName" online
4) Search "songName" by "songSubName" online

**Comment by 6A** [comment]
Implemented in be5265c57ab36dc972c8101fb79d50785b2161c9.
