### ISSUE TITLE
Version 0.4.2 online issue

### ISSUE THREAD

**Issue by Proulxs** [6A/BeatSinger#8]
Ever since I switched to version 0.4.2 I haven't seen online lyrics working properly. I've seen often the "Lyrics found online" message only to have not a single lyric displayed all through the song (I've tried various platform to make sure I wasn't hidding them)

I've also had a few song display a line early on to simply keep it displayed for what seemed to be 45-60secs.

... local lyrics work wonderfully though, thanks for this awesome mod!

**Comment by 6A** [comment]
Do you have an example map that has one of these problems? Thanks!

**Comment by Proulxs** [comment]
So I did some testing trying to find a song that had slow lyrics and.. I think I'm the one who broke it. I remember seeing once a loop of "Lyrics disabled" "Lyrinc enabled" in a song I was messing during the session where the mod stopped working

Well no lyrics work now, not even local. The initial message show up but my lyrics were disabled since last session because I didn't see the left touchpad trigger so no lyrics but though I finally found the reason why. Enabled lyrics; nothing. Left the song and came back; still no lyrics. Local or online both doesn't work now

I tried removing all mods but custom and BeatSinger and still nothing except the initial lyrics found. I deleted dll twice and reinstalled without success so far.

I just deleted the 
[BeatSinger]
Enabled=1
ToggleKeyCode=338
out of my modprefsini and something happened... now I can see the last line of local lyrics right at the start of the song, but still no online lyrics.
Here's my test-song with local lyrics that has almost no notes - it's still a WIP
[Ca fait rire les oiseaux.zip](https://github.com/6A/BeatSinger/files/2342928/Ca.fait.rire.les.oiseaux.zip)

I'll assume the strange thing I saw last session was me breaking my dll? or the mod dying before my eyes
if I have time tommorow I'll try a clean install

**Comment by 6A** [comment]
I don't think Beat Singer has anything that could give it this kind of behavior, even if you mess with it... The only thing I can think of is a problem caused by the patch, which modifies Beat Saber directly. If you don't mind, I suppose repairing via Steam / Oculus Store might fix things.

**Comment by Proulxs** [comment]
I did two clean re-install after deleting everything and making sure %appdata% got wipped too, mod still doesn't work here.

I've tested took the v0.3.1 to a v0.10 game I had stored elsewhere and with that combo the custom lyrics work but I can't make any v0.4+ version work on my up-to-date v0.11.2 game.. At least now I know where I can go to test my lyrics so I can keep my work but it's such a nice mod for party that it would be sad losing it. 
Trying to get fiber internet installed so I might eventually be able to stream my game and we could try to setup something to find the bug, in the meantime if I find something interesting I'll get in touch.

**Comment by 6A** [comment]
If you want, you can launch the game, start a song that doesn't have local lyrics, and send me the resulting logs (in `%USERPROFILE%\AppData\LocalLow\Hyperbolic Magnetism\Beat Saber\output_log.txt`), and I'll try to see what's happening. If that's not enough, I'll build a more verbose version of the plugin to troubleshoot this better.

**Comment by Proulxs** [comment]
Of course I want, this mod is the 2nd best behind Song Loader.

Here's two output logs, one with local and one without local lyrics;
[boney M local lyrics.txt](https://github.com/6A/BeatSinger/files/2343808/boney.M.local.lyrics.txt)
[Caravan Palace - Lone Digger.txt](https://github.com/6A/BeatSinger/files/2343809/Caravan.Palace.-.Lone.Digger.txt)

When I did new clean install I got newest song loader too, but no update has been on it since the v0.11.2 compatible one, so it's mandatory to have good version to even play custom songs.
Good luck!

P.S. I found where custom lyrics above my head waiting... lurking
![image](https://user-images.githubusercontent.com/42700934/44961467-970dbc80-aedf-11e8-8d82-c760cf283ac8.png)

**Comment by Proulxs** [comment]
So I removed some error from the output log that would not affect BeatSinger but might as well, added the leaderboard and BeatSaver mods back, then went back on a map with online lyrics and surprise I've received 4 lines of the lyrics (wrong timing, lasted too long) but I did receive something...
I looked over my head twice at the start and saw no lyrics, after 60sec? there was the first lyrics and sure enough over my head was a bunch of lyrics written in the sky which never showed up in front of me... here's the output of that one
[Hotel California - online.txt](https://github.com/6A/BeatSinger/files/2343815/Hotel.California.-.online.txt)
Unlike custom lyrics which display the very last line, those lines were not last and I don't think they were 4 in row

**Comment by 6A** [comment]
From what you've shown me, my bet is that for some reason the `FloatingTextSpawner` doesn't work on your end, but in this case it wouldn't really be my fault... I'll prepare another release which is much more verbose, and we'll try to fix this. 

In any case, thanks for all you did helping me troubleshoot this!

**Comment by Proulxs** [comment]
V0.11.2 has shown alot of ppl on discord come up with random issues that others don't have. I swear there are different build running around :/

Anyway send me the verbose dll on discord whenever and I'll send you report within 24h
