### ISSUE TITLE
Trouble with .srt Lyrics

### ISSUE THREAD

**Issue by Shinjula** [6A/BeatSinger#9]
I'm trying to write my own custom Lyrics files for BeatSinger. I've written a program to help reposition the subtitles so they correctly match up to the audio, but i'm having trouble getting the lyrics to display ingame. I get the "Lyrics found locally" message and no error message, and nothing in the log files that I can see but the lyrics don't turn up. Can you shed some light on where the problem might be.

I've got the lyrics in the song directory and correctly called "lyrics.srt" and this is the test file I'm currently using
[lyrics.zip](https://github.com/6A/BeatSinger/files/2516193/lyrics.zip)

**Comment by 6A** [comment]
Your file doesn't appear to have a problem. Are you sure the lyrics are enabled? (press left or right stick while in game)

**Comment by Shinjula** [comment]
Yeah tried that

**Comment by 6A** [comment]
Aww, sorry you had to resort to such a solution. I'm glad it worked though!

I don't really know what happened... Maybe a problem in the patching step performed by IPA? In any case let me know if you encounter this again.

**Comment by Shinjula** [comment]
Ooops sorry I though the issue had come back but it turned out this time I'd just had them disabled and I panicked. I dunno if this is helpful but you might want to consider making a change to the "Lyrics Found" notification when the subtitles are off (which was partly what confused me), or maybe some notification somewhere on the menu page or even ingame, probably off to the side somewhere out of the way

**Comment by Shinjula** [comment]
Oh and having the button being the same as the pause button meant that the notification of "Subtitles disabled" isn't actually visible

**Comment by 6A** [comment]
I've only tested this on an Oculus Rift, but it shouldn't be the same button as the Steam pause button. Instead it should simply toggle the lyrics without pausing the gameplay...

> you might want to consider making a change to the "Lyrics Found" notification when the subtitles are off

I was actually debating this myself. I thought it was nice to have some feedback even though the lyrics are off, but I suppose your idea is better.

**Comment by Shinjula** [comment]
Pressing down on the controllers does pause the gameplay on the steam version. This is including when your plugin isnt present.
